backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow
  media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
  public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Cover", name: "cover", widget: "string"}
      
  